### ISSUE TITLE
Bundle dev command [question]

### ISSUE THREAD

**Issue by acerbisgianluca** [jovotech/jovo-v4-template#14]
Hi, I'm new to Typescript and I'm looking at the scripts in `package.json`. Shouldn't `bundle:dev` be called on `dist/app.dev.js` instead of `src/app.dev.ts`? Do I have to add `npm run tsc` in `prebundle` command? Thanks

**Comment by aswetlow** [comment]
Hey @acerbisgianluca 
`esbuild` takes care of "everything" :) 

`npm run tsc` isn't required in `prebundle`

**Comment by acerbisgianluca** [comment]
Got it, thank you again!
